tools/perf: Include inttypes.h to avoid error in cs-etm.c
PRIx64 macro was not defined and this error occours:

| util/cs-etm.c:1264:40: error: expected '}' before 'PRIx64'
|    [CS_ETM_MAGIC] = "   Magic number  %"PRIx64"\n",
	|                                         ^~~~~~

This was introduced by commit 362f8417b1cc ("opencsd: This is a
Backport of the Following") from axxia branches. This backport was
done in 4.9 Kernel where inttypes.h was included through
tools/perf/util/util.h.

After porting in 4.12 Kernel, this error occours because starting with
commit c3dca1a1c0ec ("perf tools: Remove PRI[xu] macros from perf.h"),
inttypes.h was not included in util.h.

So, include inttypes.h directly in cs-etm.c to fix this.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>